"""Code-corpus streaming pipeline for "le fat chaton" (lazy init).

Same memmap idea as data2.py but for CODE corpora (Stack v2 / StarCoderData /
the-smol-corpus). Designed to run on a CLOUD VM (more disk than your 2070 box —
Stack v2 is huge, so we stream + sample, never pull the whole thing).

Pick the corpus with CHATON_CODE_CORPUS:
  "github-code-python" (DEFAULT) -> codeparrot/github-code filtered to Python.
                      Fully open, no gating/acceptance needed. Streams fast as
                      parquet from HF. The workhorse for a solo-budget coder.
  "python-edu"      -> HuggingFaceTB/smollm-corpus python-edu (7.6M edu-scored
                      Python files). Higher quality per token, open, but the
                      file bodies may need SWH S3 fetch (slower).
  "starcoderdata"   -> bigcode/starcoderdata python subset. GATED (accept terms
                      once at huggingface.co/datasets/bigcode/starcoderdata).
  "cosmopedia"      -> smollm-corpus synthetic textbooks (prose). Used as the
                      PROSE_BLEND for general knowledge, not a code source.
  "fineweb-edu"     -> smollm-corpus fineweb-edu-dedup (educational web). Prose.

Like data2.py: encodes once to a uint16 memmap, then streams random windows.
For a coding model the vocab stays 50257 (gpt2 BPE) — code tokenizes fine with it,
and keeping the vocab shared with the WikiText base lets you continue-pretrain
on top of an existing checkpoint if you want.
(For the BIG fat model you train from scratch, so no checkpoint reuse needed.)

Imports are side-effect free — preparation (download, tokenize, memmap, GPU
upload) happens lazily on the first call to ``get_batch``.
"""
import ast
import os
import random
import numpy as np
import torch
from tokenizer import VOCAB_SIZE

CORPUS = os.environ.get("CHATON_CODE_CORPUS", "starcoderdata")
BLOCK = int(os.environ.get("CHATON_CODE_BLOCK", "4096"))   # match config.block_size

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# memmap files namespaced by corpus + vocab (switching corpus rebuilds)
_TAG = f"{CORPUS}_v{VOCAB_SIZE}"
TRAIN_BIN = f"code_train_{_TAG}.bin"
VAL_BIN = f"code_val_{_TAG}.bin"
VAL_GPU_TOKENS = 262144   # fixed val shard on GPU for fast eval

# Prose blend: a fraction of training tokens come from general text so the
# model keeps broad language knowledge (the Qwen-Coder recipe — general
# knowledge via the CORPUS MIX, not a warm-start). 0 = code only.
PROSE_BLEND = float(os.environ.get("CHATON_PROSE_BLEND", "0.15"))
# Syntax validation: skip Python files that don't parse.  Catches broken files,
# autogenerated stubs, and binary blobs mislabelled as Python.
VALIDATE_SYNTAX = os.environ.get("CHATON_VALIDATE_SYNTAX", "1") == "1"
# Educational quality filter: skip code files below this threshold (0-1).
# 0 = off (keep everything), 0.3 = lenient, 0.5 = recommended, 0.7 = aggressive.
# Only applies to code streams (not prose blend).
MIN_EDU_SCORE = float(os.environ.get("CHATON_MIN_EDU_SCORE", "0.0"))

# Lazy-initialised globals — set on first get_batch call.
_train_mmap: np.memmap | None = None
_val_mmap: np.memmap | None = None
_val_tensor_gpu: torch.Tensor | None = None


def _stream_one(name: str, max_docs: int | None = None):
    """Yield text strings from ONE corpus (streamed from HuggingFace).

    max_docs caps how many docs to pull — keeps the memmap build bounded on a
    free-tier VM with limited disk/time.
    """
    try:
        from datasets import load_dataset
    except ImportError:
        raise ImportError(
            "datasets library required for code data pipeline. "
            "Install with: pip install datasets>=2.14"
        )
    if name == "python-edu":
        ds = load_dataset("HuggingFaceTB/smollm-corpus", "python-edu",
                          split="train", streaming=True)
        for i, row in enumerate(ds):
            if max_docs and i >= max_docs:
                break
            yield row.get("text") or row.get("content") or ""
    elif name == "github-code-python":
        ds = load_dataset("codeparrot/github-code", split="train",
                          languages=["Python"], streaming=True)
        for i, row in enumerate(ds):
            if max_docs and i >= max_docs:
                break
            yield row.get("code") or row.get("content") or ""
    elif name == "starcoderdata":
        ds = load_dataset("bigcode/starcoderdata", split="train",
                          data_dir="python", streaming=True)
        for i, row in enumerate(ds):
            if max_docs and i >= max_docs:
                break
            yield row.get("content") or ""
    elif name == "cosmopedia":
        ds = load_dataset("HuggingFaceTB/smollm-corpus", "cosmopedia-v2",
                          split="train", streaming=True)
        for i, row in enumerate(ds):
            if max_docs and i >= max_docs:
                break
            yield row.get("text") or row.get("content") or ""
    elif name == "fineweb-edu":
        ds = load_dataset("HuggingFaceTB/smollm-corpus", "fineweb-edu-dedup",
                          split="train", streaming=True)
        for i, row in enumerate(ds):
            if max_docs and i >= max_docs:
                break
            yield row.get("text") or row.get("content") or ""
    else:
        raise ValueError(
            f"unknown code corpus {name!r}. Valid: python-edu, starcoderdata, "
            "cosmopedia, fineweb-edu")


def _encode_streamed(stream, max_tokens: int, eot: int):
    """Encode a text stream into a flat token list, capped at max_tokens."""
    from tokenizer import encode
    out: list[int] = []
    total = 0
    for text in stream:
        if not text or not text.strip():
            continue
        ids = encode(text) + [eot]   # EOT between docs
        out.extend(ids)
        total += len(ids)
        if total >= max_tokens:
            break
    return out, total


def _educational_score(text: str) -> float:
    """Heuristic educational quality score for a Python code file (0-1).

    Combines several signals that correlate with high-quality, educational code:
    - Docstrings (strong signal: the author documented the code)
    - Comments (moderate signal: reasoning is explained)
    - Type hints (modern Python practice)
    - Test patterns (code with tests is more reliable)
    - Meaningful identifiers (not single-letter variables everywhere)
    - Length diversity (autogenerated files are often very uniform)

    Threshold guide:
      0.0 = off (keep everything)
      0.3 = lenient (removes only autogenerated/empty files)
      0.5 = recommended (Phi-3/VLM-style: educational code)
      0.7 = aggressive (only well-documented, typed, tested code)
    """
    import re
    lines = text.splitlines()
    if not lines:
        return 0.0
    n_lines = len(lines)

    # --- Heuristic 1: Docstrings (0-0.3) ---
    ds_count = len(re.findall(r'"""|"""', text)) // 2
    docstring_bonus = min(0.3, ds_count * 0.15) if ds_count > 0 else 0.0

    # --- Heuristic 2: Comments (0-0.25) ---
    full_comment = sum(1 for l in lines if l.strip().startswith("#"))
    inline_comment = sum(
        1 for l in lines if "#" in l and not l.strip().startswith("#")
    )
    comment_ratio = (full_comment + inline_comment * 0.5) / max(1, n_lines)
    if comment_ratio < 0.02:
        comment_score = 0.0
    elif comment_ratio < 0.15:
        comment_score = min(0.25, comment_ratio * 3.0)
    else:
        comment_score = min(0.25, 0.25)

    # --- Heuristic 3: Type hints (0-0.2) ---
    type_hits = re.findall(
        r':\s*(?:int|str|float|bool|list\[|dict\[|tuple|set|Optional|Union|Any|Callable|None)\b',
        text,
    )
    type_score = min(0.2, len(type_hits) * 0.04)

    # --- Heuristic 4: Test patterns (0-0.1) ---
    test_hits = re.findall(
        r'\b(?:assert |pytest|unittest|def test_|TestCase)', text
    )
    test_score = min(0.1, len(test_hits) * 0.02)

    # --- Heuristic 5: Identifier quality (0-0.1) ---
    idents = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]{0,30}\b', text)
    keywords = {
        'if', 'else', 'for', 'while', 'def', 'class', 'return',
        'import', 'from', 'in', 'not', 'and', 'or', 'is', 'None',
        'True', 'False', 'try', 'except', 'finally', 'with', 'pass',
        'break', 'continue', 'raise', 'yield', 'lambda', 'self', 'print',
        'range', 'len', 'int', 'str', 'float', 'list', 'dict', 'set',
        'type', 'map', 'filter', 'zip',
    }
    user_names = [
        n for n in idents
        if n not in keywords and len(n) > 1 and not n.startswith('_')
    ]
    avg_len = sum(len(n) for n in user_names) / len(user_names) if user_names else 0
    if avg_len < 2:
        ident_score = 0.0
    elif avg_len < 4:
        ident_score = (avg_len - 2) * 0.05
    elif avg_len <= 10:
        ident_score = 0.1
    else:
        ident_score = max(0.0, 0.1 - (avg_len - 10) * 0.005)

    # --- Heuristic 6: Length diversity (0-0.05) ---
    if n_lines >= 5:
        line_lens = [len(l) for l in lines]
        mean_ll = sum(line_lens) / n_lines
        var_ll = sum((l - mean_ll) ** 2 for l in line_lens) / n_lines
        cv = (var_ll ** 0.5) / max(1.0, mean_ll)
        diversity_score = min(0.05, max(0.0, cv * 0.05))
    else:
        diversity_score = 0.0

    return min(1.0, docstring_bonus + comment_score + type_score
               + test_score + ident_score + diversity_score)


def _collect_documents(stream, max_tokens: int, max_docs: int | None,
                       eot: int, validate_syntax: bool = False,
                       min_edu_score: float = 0.0):
    """Encode a text stream into a list of per-document token lists.

    Each element is ``(tokens, n_tokens)`` where *tokens* includes a trailing
    EOT.  Stops when *max_tokens* or *max_docs* is reached.

    If *validate_syntax* is True (only for Python code streams), each document
    is first checked with ``compile()`` and skipped if it doesn't parse — this
    prevents the model from learning invalid syntax patterns.

    If *min_edu_score* > 0, each document is scored for educational value and
    skipped if below the threshold.  Only applies to code (not prose blends).
    """
    from tokenizer import encode
    docs: list[tuple[list[int], int]] = []
    total = 0
    doc_count = 0
    skipped_syntax = 0
    skipped_edu = 0
    skipped_dedup = 0
    texts_collected: list[str] = []  # for dedup, store raw text briefly

    for text in stream:
        if max_docs and doc_count >= max_docs:
            break
        if not text or not text.strip():
            continue

        # Syntax validation: skip files that don't parse as valid Python.
        if validate_syntax:
            try:
                compile(text, "<corpus>", "exec",
                        flags=ast.PyCF_ONLY_AST, dont_inherit=True)
            except SyntaxError:
                skipped_syntax += 1
                continue

        # Educational quality filter: skip low-value files.
        if min_edu_score > 0:
            score = _educational_score(text)
            if score < min_edu_score:
                skipped_edu += 1
                continue

        texts_collected.append(text)
        doc_count += 1

    # --- Near-deduplication via MinHash + LSH (if enabled) -----------------
    dedup_threshold = float(os.environ.get("CHATON_DEDUP_THRESHOLD", "0.85"))
    if dedup_threshold > 0.0 and len(texts_collected) > 1:
        keep_mask = _minhash_dedup(texts_collected, threshold=dedup_threshold)
        n_before = len(texts_collected)
        texts_collected = [t for t, keep in zip(texts_collected, keep_mask) if keep]
        skipped_dedup = n_before - len(texts_collected)
        print(f"[code] near-dedup: kept {len(texts_collected)}/{n_before} "
              f"(threshold={dedup_threshold}, removed {skipped_dedup})")

    # --- Encode surviving documents ---------------------------------------
    for text in texts_collected:
        ids = encode(text) + [eot]
        docs.append((ids, len(ids)))
        total += len(ids)
        if max_tokens and total >= max_tokens:
            break

    if skipped_syntax:
        print(f"[code] syntax validation: skipped {skipped_syntax} non-parsing files")
    if skipped_edu:
        print(f"[code] educational filter: skipped {skipped_edu} low-value files "
              f"(threshold={min_edu_score})")
    return docs, total


# ---------------------------------------------------------------------------
# MinHash-based near-deduplication (for code corpora)
# ---------------------------------------------------------------------------

_NGRAM = 5  # character 5-grams for code (sensitive to whitespace/tokens)
_N_HASHES = 128
_N_BANDS = 16  # LSH bands: 128 / 16 = 8 hashes per band
_HASHES_PER_BAND = _N_HASHES // _N_BANDS
_DEDUP_SEED = 42


def _make_minhash_hashes(seed: int):
    """Generate *N_HASHES* random hash functions using the (a*x + b) % p
    universal hashing scheme.  Returns list of (a, b) tuples."""
    rng = random.Random(seed)
    p = (1 << 61) - 1  # Mersenne prime (large enough to avoid collisions)
    return [(rng.randint(1, p - 1), rng.randint(0, p - 1)) for _ in range(_N_HASHES)]


def _minhash_signature(text: str, hash_fns: list[tuple[int, int]]) -> list[int]:
    """Compute the MinHash signature for *text* using the given hash functions.

    The signature is a list of ``min(s_{h_i}(shingle))`` over all shingles,
    where *s_{h_i}* is the i-th hash function.

    Uses character *NGRAM*-shingles — overlapping substrings of length NGRAM.
    """
    p = (1 << 61) - 1
    sig = [p] * _N_HASHES

    # Slide over character n-grams
    for i in range(len(text) - _NGRAM + 1):
        shingle = text[i:i + _NGRAM]
        shingle_hash = hash(shingle) & 0xFFFFFFFF  # 32-bit hash
        # Apply each hash function
        for j, (a, b) in enumerate(hash_fns):
            h = (a * shingle_hash + b) % p
            if h < sig[j]:
                sig[j] = h
    return sig


def _lsh_buckets(signature: list[int]) -> list[tuple[int, int]]:
    """Convert a MinHash signature into LSH band buckets.

    Returns a list of ``(band_idx, band_hash)`` tuples — one per band.
    Documents that share a band hash are candidate near-duplicates.
    """
    buckets: list[tuple[int, int]] = []
    for band in range(_N_BANDS):
        start = band * _HASHES_PER_BAND
        end = start + _HASHES_PER_BAND
        # Hash the band's hashes together using Python's built-in hash
        band_hash = hash(tuple(signature[start:end]))
        buckets.append((band, band_hash))
    return buckets


def _jaccard_from_signatures(sig_a: list[int], sig_b: list[int]) -> float:
    """Estimate Jaccard similarity from MinHash signatures.

    J(sig_a, sig_b) ≈ |{i : sig_a[i] == sig_b[i]}| / N_HASHES
    """
    matches = sum(1 for a, b in zip(sig_a, sig_b) if a == b)
    return matches / _N_HASHES


def _minhash_dedup(texts: list[str], threshold: float = 0.85) -> list[bool]:
    """MinHash-based near-deduplication with LSH.

    Args:
        texts: List of raw document texts.
        threshold: Jaccard similarity threshold for duplicate detection.

    Returns:
        Boolean mask: True = keep, False = duplicate.
        The FIRST document in each cluster is kept; all others are flagged.
    """
    if len(texts) < 2:
        return [True] * len(texts)

    hash_fns = _make_minhash_hashes(_DEDUP_SEED)

    print(f"[minhash] computing {_N_HASHES}-hash signatures for {len(texts)} docs...")
    signatures: list[list[int]] = []
    for t in texts:
        sig = _minhash_signature(t, hash_fns)
        signatures.append(sig)

    # LSH: build band → bucket_hash → list of doc indices
    buckets: dict[tuple[int, int], list[int]] = {}
    for doc_idx, sig in enumerate(signatures):
        for band, band_hash in _lsh_buckets(sig):
            key = (band, band_hash)
            if key not in buckets:
                buckets[key] = []
            buckets[key].append(doc_idx)

    # Build graph of candidate pairs (documents sharing any bucket)
    # Use union-find to cluster connected components
    parent = list(range(len(texts)))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        px, py = find(x), find(y)
        if px != py:
            parent[px] = py

    # For each bucket with multiple docs, union them (candidate duplicates)
    for bucket_docs in buckets.values():
        if len(bucket_docs) < 2:
            continue
        # Check each pair within a small bucket (fast for small clusters)
        if len(bucket_docs) <= 20:
            for i in range(len(bucket_docs)):
                for j in range(i + 1, len(bucket_docs)):
                    idx_i = bucket_docs[i]
                    idx_j = bucket_docs[j]
                    if find(idx_i) == find(idx_j):
                        continue  # already in same cluster
                    sim = _jaccard_from_signatures(
                        signatures[idx_i], signatures[idx_j]
                    )
                    if sim >= threshold:
                        union(idx_i, idx_j)
        else:
            # Large bucket: just union all (conservative — may over-merge)
            first = bucket_docs[0]
            for doc_idx in bucket_docs[1:]:
                sim = _jaccard_from_signatures(signatures[first], signatures[doc_idx])
                if sim >= threshold:
                    union(first, doc_idx)

    # Cluster roots
    cluster_ids: dict[int, int] = {}
    next_cluster = 0
    doc_to_cluster = [0] * len(texts)
    for i in range(len(texts)):
        root = find(i)
        if root not in cluster_ids:
            cluster_ids[root] = next_cluster
            next_cluster += 1
        doc_to_cluster[i] = cluster_ids[root]

    # Keep the FIRST document in each cluster
    kept_first: set[int] = set()
    keep_mask: list[bool] = []
    for i, cluster in enumerate(doc_to_cluster):
        if cluster not in kept_first:
            kept_first.add(cluster)
            keep_mask.append(True)
        else:
            keep_mask.append(False)

    n_clusters = len(kept_first)
    n_dupes = len(texts) - n_clusters
    print(f"[minhash] {n_clusters} clusters, {n_dupes} duplicates removed")
    return keep_mask


def _interleave_documents(
    code_docs: list[tuple[list[int], int]],
    prose_docs: list[tuple[list[int], int]],
    seed: int = 1337,
) -> list[int]:
    """Interleave code and prose documents at the document level.

    Returns a flat token list where the boundary between two documents always
    falls at a document boundary (never mid-document).  Documents from the
    smaller source are spread evenly among the larger source.

    This is what Qwen-Coder / DeepSeek-Coder actually do — training sequences
    contain tokens from at most 1-2 complete documents, preserving natural
    intra-document transitions.
    """
    rng = np.random.default_rng(seed)

    # Shuffle documents within each pool
    rng.shuffle(code_docs)
    rng.shuffle(prose_docs)

    # Build a flat list of document token-lists, interleaved
    # (code, prose, code, prose, …) or (prose, code, prose, code, …)
    interleaved_docs: list[list[int]] = []
    c_idx, p_idx = 0, 0
    # Randomly decide which source goes first
    turn = 0 if rng.random() < 0.5 else 1  # 0=code, 1=prose
    sources = [code_docs, prose_docs]

    while c_idx < len(code_docs) and p_idx < len(prose_docs):
        src_idx = 0 if turn == 0 else 1
        doc = sources[src_idx]
        if src_idx == 0:
            interleaved_docs.append(code_docs[c_idx][0])
            c_idx += 1
        else:
            interleaved_docs.append(prose_docs[p_idx][0])
            p_idx += 1
        turn = 1 - turn  # alternate

    # Append remaining docs from whichever source has leftovers
    while c_idx < len(code_docs):
        interleaved_docs.append(code_docs[c_idx][0])
        c_idx += 1
    while p_idx < len(prose_docs):
        interleaved_docs.append(prose_docs[p_idx][0])
        p_idx += 1

    # Flatten to a single token list
    result: list[int] = []
    for doc_tokens in interleaved_docs:
        result.extend(doc_tokens)
    return result


def _prepare():
    """Encode a bounded number of corpus docs to a uint16 memmap. One-time per
    VM. Blends in PROSE_BLEND fraction of cosmopedia (general knowledge) per
    the Qwen-Coder recipe.

    Idempotent: subsequent calls return the already-constructed memmaps.
    """
    global _train_mmap, _val_mmap, _val_tensor_gpu  # noqa: PLW0603
    from tokenizer import EOT_TOKEN

    if _train_mmap is not None and _val_mmap is not None:
        return _train_mmap, _val_mmap

    max_docs = int(os.environ.get("CHATON_CODE_MAX_DOCS", "200000"))

    if not (os.path.exists(TRAIN_BIN) and os.path.exists(VAL_BIN)):
        max_tokens = int(os.environ.get("CHATON_CODE_MAX_TOKENS", str(50_000_000)))
        print(f"[code] encoding corpus {CORPUS!r} (cap {max_tokens:,} tokens, "
              f"prose blend {PROSE_BLEND:.0%})...")
        code_docs, code_total = _collect_documents(
            _stream_one(CORPUS, max_docs=max_docs), max_tokens, max_docs, EOT_TOKEN,
            validate_syntax=VALIDATE_SYNTAX)
        if PROSE_BLEND > 0:
            prose_budget = int(code_total * PROSE_BLEND / max(1 - PROSE_BLEND, 1e-3))
            print(f"[code] blending {prose_budget:,} prose tokens from cosmopedia...")
            prose_docs, _ = _collect_documents(
                _stream_one("cosmopedia", max_docs=max_docs),
                prose_budget, max_docs, EOT_TOKEN, validate_syntax=False)
        else:
            prose_docs = []

        # Document-level interleaving — each training window sees one complete
        # document at a time, not a mix of token fragments from different docs.
        all_ids = _interleave_documents(code_docs, prose_docs, seed=1337)
        total = len(all_ids)
        if total == 0:
            raise RuntimeError(f"no tokens encoded from {CORPUS} — check dataset name/access")
        arr = np.array(all_ids, dtype=np.int64)
        # shuffle so code+prose interleave (not two contiguous blocks)
        np.random.default_rng(1337).shuffle(arr)
        split = int(0.98 * len(arr))   # tiny val (code val is less meaningful)
        train = arr[:split].astype(np.uint16)
        val = arr[split:].astype(np.uint16)
        train.tofile(TRAIN_BIN)
        val.tofile(VAL_BIN)
        print(f"[code] {len(train):,} train | {len(val):,} val tokens written "
              f"({len(code_docs)} code docs + {len(prose_docs)} prose docs)")
    else:
        print("[code] memmap files already exist, skipping encode")

    _train_mmap = np.memmap(TRAIN_BIN, dtype=np.uint16, mode="r")
    _val_mmap = np.memmap(VAL_BIN, dtype=np.uint16, mode="r")

    _val_len = min(VAL_GPU_TOKENS, len(_val_mmap) - BLOCK - 1)
    _val_tensor_gpu = torch.from_numpy(
        np.array(_val_mmap[:_val_len], dtype=np.int64)
    ).to(device)

    return _train_mmap, _val_mmap


def get_batch(split: str, batch_size: int, block_size: int):
    """Random-window batch from the code corpus.

    The first call triggers preparation (download + tokenize + memmap + GPU
    upload). Subsequent calls stream from the already-loaded memmaps.
    """
    train_mmap, val_mmap = _prepare()

    if split == "val":
        max_start = _val_tensor_gpu.size(0) - block_size - 1
        starts = torch.randint(max_start, (batch_size,), device=device)
        x = torch.stack([_val_tensor_gpu[i:i + block_size] for i in starts])
        y = torch.stack([_val_tensor_gpu[i + 1:i + block_size + 1] for i in starts])
        return x, y

    mmap = train_mmap
    max_start = len(mmap) - block_size - 1
    starts = np.random.randint(0, max_start, size=batch_size)
    xs = np.stack([mmap[s:s + block_size].astype(np.int64) for s in starts])
    ys = np.stack([mmap[s + 1:s + block_size + 1].astype(np.int64) for s in starts])
    return torch.from_numpy(xs).to(device), torch.from_numpy(ys).to(device)


if __name__ == "__main__":
    print("corpus:", CORPUS, "| block:", BLOCK)
    x, y = get_batch("train", 2, min(BLOCK, 512))
    print("train batch:", tuple(x.shape), "| device", x.device)
    from tokenizer import decode
    print("sample text:", decode(x[0][:40].tolist())[:200])